image:
  repository: salmonstone/cloudpilot
  tag: latest
  pullPolicy: Always

frontend:
  image:
    repository: salmonstone/cloudpilot-frontend
    tag: latest

replicaCount: 2

service:
  type: ClusterIP
  port: 8000

resources:
  requests: {cpu: 150m, memory: 256Mi}
  limits:   {cpu: 600m, memory: 768Mi}

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

env:
  - name: GROQ_API_KEY
    valueFrom:
      secretKeyRef:
        name: cloudpilot-secrets
        key: GROQ_API_KEY
  - name: AWS_DEFAULT_REGION
    value: ap-south-1
